deployment:
  replicaCount: 1
  image:
    repository: y4m4/s3www
    tag: "latest"
  targetPort: 8080
    
service:
  type: ClusterIP
  port: 8080

ingress:
  minioConsole:
    host: con.minio.cluster.local
    backend:
      service: minio
      port: 9001
  minioApi: 
    host: api.minio.cluster.local
    backend:
      service: minio
      port: 9000
  s3www: 
    host: app1.cluster.local
    backend:
      service: app1-s3www

minio:
  service: 
