deployment:
  replicaCount: 1
  image:
    repository: y4m4/s3www
    tag: "latest"
  targetPort: 8080
    
service:
  type: ClusterIP
  port: 8080

ingress:
  minio:
    service: "minio" 
    console:
      host: con.minio.cluster.local
      port: 9001
    api: 
      host: api.minio.cluster.local
      port: 9000
  s3www: 
    host: app1.cluster.local
    service: app1-s3www
