apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3www
  labels:
    app: s3www
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: s3www
  template:
    metadata:
      labels:
        app: s3www
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "y4m4/s3www:latest"
          args:
          - "-endpoint "http://my-release-minio.default.svc.cluster.local:9000"
          - "-accessKey kara"
          - "-secretKey Go@d1ife"
          - "-bucket test" 
          - "-address 0.0.0.0:8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP