apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3www.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "s3www.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "s3www.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          args:
          - "-endpoint"
          - "http://{{ include "s3www.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:9000"
          - "-accessKey" 
          - "{{ .Values.deployment.minio.accessKey }}
          - "-secretKey"
          - "{{ .Values.deployment.minio.secretKey }}
          - "-bucket"
          - "{{ .Values.deployment.minio.bucket }}
          - "-address"
          - "0.0.0.0:8080"
          ports:
            - name: http
              containerPort: {{ .Values.deployment.targetPort }}
              protocol: TCP
