apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3www.fullname" . }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
          - "-endpoint"
          - "http://my-release-minio.default.svc.cluster.local:9000"
          - "-accessKey" 
          - "kara"
          - "-secretKey"
          - "Go@d1ife"
          - "-bucket"
          - "test" 
          - "-address"
          - "0.0.0.0:8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP