apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "s3www.fullname" }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.minioConsole.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.minioConsole.backend.service }}
                port: 
                  number: {{ .Values.ingress.minioConsole.backend.port }}
    - host: {{ .Values.ingress.minioApi.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.minioApi.backend.service }}
                port: 
                  number: {{ .Values.ingress.minioApi.backend.port }}
    - host: {{ .Values.ingress.s3www.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "s3www.fullname" }}
                port: 
                  number: {{ .Values.service.port }}